const mockFeeds = [
  {
    id: '1',
    profilePicture: 'https://i.pravatar.cc/300?img=1',
    name: 'Alice Johnson',
    role: 'Software Engineer',
    company: 'ABC Corp',
    postContent: 'Excited to work on our new project! #softwaredevelopment',
    historyJobs: [
      {
        role: 'Junior Developer',
        companyName: 'TechStart',
        description: 'Worked on web application development.',
        startDate: new Date('2020-01-01'),
        endDate: new Date('2021-02-15'),
      },
      {
        role: 'Software Engineer Intern',
        companyName: 'TechGrowth',
        description: 'Assisted in developing software solutions.',
        startDate: new Date('2019-06-01'),
        endDate: new Date('2019-12-31'),
      },
      {
        role: 'Student Developer',
        companyName: 'University Labs',
        description: 'Contributed to research projects.',
        startDate: new Date('2018-09-01'),
        endDate: new Date('2019-05-31'),
      },
    ],
  },
  {
    id: '2',
    profilePicture: 'https://i.pravatar.cc/300?img=32',
    name: 'Jane Smith',
    role: 'Product Manager',
    company: 'XYZ Inc',
    postContent: 'Just launched our latest product. Check it out!',
    historyJobs: [
      {
        role: 'Product Manager',
        companyName: 'XYZ Inc',
        description: 'Led product development for our flagship product.',
        startDate: new Date('2019-03-01'),
        endDate: new Date('2021-09-30'),
      },
      {
        role: 'Associate Product Manager',
        companyName: 'XYZ Inc',
        description: 'Assisted in product management tasks.',
        startDate: new Date('2018-06-01'),
        endDate: new Date('2019-02-28'),
      },
      {
        role: 'Product Analyst Intern',
        companyName: 'TechAnalysis',
        description: 'Analyzed market trends and competitor data.',
        startDate: new Date('2017-06-01'),
        endDate: new Date('2017-12-31'),
      },
    ],
  },
  {
    id: '3',
    profilePicture: 'https://i.pravatar.cc/300?img=3',
    name: 'John Doe',
    role: 'UI/UX Designer',
    company: 'DesignCo',
    postContent: 'Designing a new user interface for a client project.',
    historyJobs: [
      {
        role: 'UI/UX Designer',
        companyName: 'DesignCo',
        description: 'Created user-friendly interfaces for web and mobile applications.',
        startDate: new Date('2019-02-01'),
        endDate: new Date('2022-08-31'),
      },
      {
        role: 'Graphic Designer',
        companyName: 'CreativeDesigns',
        description: 'Designed marketing materials and branding assets.',
        startDate: new Date('2018-05-01'),
        endDate: new Date('2019-01-31'),
      },
      {
        role: 'Design Intern',
        companyName: 'DesignInternship',
        description: 'Learned design principles and tools.',
        startDate: new Date('2017-06-01'),
        endDate: new Date('2017-12-31'),
      },
    ],
  },
  {
    id: '4',
    profilePicture: 'https://i.pravatar.cc/300?img=4',
    name: 'Bob Anderson',
    role: 'Marketing Manager',
    company: 'MarketingPro',
    postContent: 'Launching a marketing campaign next week. Stay tuned!',
    historyJobs: [
      {
        role: 'UI/UX Designer',
        companyName: 'DesignCo',
        description: 'Created user-friendly interfaces for web and mobile applications.',
        startDate: new Date('2019-02-01'),
        endDate: new Date('2022-08-31'),
      },
      {
        role: 'Graphic Designer',
        companyName: 'CreativeDesigns',
        description: 'Designed marketing materials and branding assets.',
        startDate: new Date('2018-05-01'),
        endDate: new Date('2019-01-31'),
      },
      {
        role: 'Design Intern',
        companyName: 'DesignInternship',
        description: 'Learned design principles and tools.',
        startDate: new Date('2017-06-01'),
        endDate: new Date('2017-12-31'),
      },
    ],
  },
  {
    id: '5',
    profilePicture: 'https://i.pravatar.cc/300?img=5',
    name: 'Eva Brown',
    role: 'Data Scientist',
    company: 'DataTech',
    postContent: 'Analyzing data trends for our latest project.',
    historyJobs: [
      {
        role: 'UI/UX Designer',
        companyName: 'DesignCo',
        description: 'Created user-friendly interfaces for web and mobile applications.',
        startDate: new Date('2019-02-01'),
        endDate: new Date('2022-08-31'),
      },
      {
        role: 'Graphic Designer',
        companyName: 'CreativeDesigns',
        description: 'Designed marketing materials and branding assets.',
        startDate: new Date('2018-05-01'),
        endDate: new Date('2019-01-31'),
      },
      {
        role: 'Design Intern',
        companyName: 'DesignInternship',
        description: 'Learned design principles and tools.',
        startDate: new Date('2017-06-01'),
        endDate: new Date('2017-12-31'),
      },
    ],
  },
  {
    id: '6',
    profilePicture: 'https://i.pravatar.cc/300?img=6',
    name: 'Michael Lee',
    role: 'Frontend Developer',
    company: 'WebDev Solutions',
    postContent: 'Just launched a new website. Feedback welcome!',
    historyJobs: [
      {
        role: 'UI/UX Designer',
        companyName: 'DesignCo',
        description: 'Created user-friendly interfaces for web and mobile applications.',
        startDate: new Date('2019-02-01'),
        endDate: new Date('2022-08-31'),
      },
      {
        role: 'Graphic Designer',
        companyName: 'CreativeDesigns',
        description: 'Designed marketing materials and branding assets.',
        startDate: new Date('2018-05-01'),
        endDate: new Date('2019-01-31'),
      },
      {
        role: 'Design Intern',
        companyName: 'DesignInternship',
        description: 'Learned design principles and tools.',
        startDate: new Date('2017-06-01'),
        endDate: new Date('2017-12-31'),
      },
    ],
  },
  {
    id: '7',
    profilePicture: 'https://i.pravatar.cc/300?img=7',
    name: 'Samuel White',
    role: 'HR Manager',
    company: 'HR Solutions',
    postContent: 'We are hiring! Looking for HR professionals to join our team.',
    historyJobs: [
      {
        role: 'UI/UX Designer',
        companyName: 'DesignCo',
        description: 'Created user-friendly interfaces for web and mobile applications.',
        startDate: new Date('2019-02-01'),
        endDate: new Date('2022-08-31'),
      },
      {
        role: 'Graphic Designer',
        companyName: 'CreativeDesigns',
        description: 'Designed marketing materials and branding assets.',
        startDate: new Date('2018-05-01'),
        endDate: new Date('2019-01-31'),
      },
      {
        role: 'Design Intern',
        companyName: 'DesignInternship',
        description: 'Learned design principles and tools.',
        startDate: new Date('2017-06-01'),
        endDate: new Date('2017-12-31'),
      },
    ],
  },
  {
    id: '8',
    profilePicture: 'https://i.pravatar.cc/300?img=8',
    name: 'David Clark',
    role: 'Financial Analyst',
    company: 'FinanceCorp',
    postContent: 'Just published a financial report with key insights.',
    historyJobs: [
      {
        role: 'UI/UX Designer',
        companyName: 'DesignCo',
        description: 'Created user-friendly interfaces for web and mobile applications.',
        startDate: new Date('2019-02-01'),
        endDate: new Date('2022-08-31'),
      },
      {
        role: 'Graphic Designer',
        companyName: 'CreativeDesigns',
        description: 'Designed marketing materials and branding assets.',
        startDate: new Date('2018-05-01'),
        endDate: new Date('2019-01-31'),
      },
      {
        role: 'Design Intern',
        companyName: 'DesignInternship',
        description: 'Learned design principles and tools.',
        startDate: new Date('2017-06-01'),
        endDate: new Date('2017-12-31'),
      },
    ],
  },
  {
    id: '9',
    profilePicture: 'https://i.pravatar.cc/300?img=9',
    name: 'Olivia Green',
    role: 'Content Writer',
    company: 'ContentCreators',
    postContent: 'Wrote a new article on content marketing strategies.',
    historyJobs: [
      {
        role: 'UI/UX Designer',
        companyName: 'DesignCo',
        description: 'Created user-friendly interfaces for web and mobile applications.',
        startDate: new Date('2019-02-01'),
        endDate: new Date('2022-08-31'),
      },
      {
        role: 'Graphic Designer',
        companyName: 'CreativeDesigns',
        description: 'Designed marketing materials and branding assets.',
        startDate: new Date('2018-05-01'),
        endDate: new Date('2019-01-31'),
      },
      {
        role: 'Design Intern',
        companyName: 'DesignInternship',
        description: 'Learned design principles and tools.',
        startDate: new Date('2017-06-01'),
        endDate: new Date('2017-12-31'),
      },
    ],
  },
  {
    id: '10',
    profilePicture: 'https://i.pravatar.cc/300?img=10',
    name: 'Sarah Taylor',
    role: 'Product Designer',
    company: 'DesignCo',
    postContent: 'Designing a user-friendly mobile app. User experience matters most!',
    historyJobs: [
      {
        role: 'UI/UX Designer',
        companyName: 'DesignCo',
        description: 'Created user-friendly interfaces for web and mobile applications.',
        startDate: new Date('2019-02-01'),
        endDate: new Date('2022-08-31'),
      },
      {
        role: 'Graphic Designer',
        companyName: 'CreativeDesigns',
        description: 'Designed marketing materials and branding assets.',
        startDate: new Date('2018-05-01'),
        endDate: new Date('2019-01-31'),
      },
      {
        role: 'Design Intern',
        companyName: 'DesignInternship',
        description: 'Learned design principles and tools.',
        startDate: new Date('2017-06-01'),
        endDate: new Date('2017-12-31'),
      },
    ],
  },
];

export { mockFeeds };
